version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: quiz-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz-db
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d